# Task 6: hit-and-run accident
On 11.08.2010, there was a hit-and-run accident. The license plate of the car involved is unknown. The police have asked for your assistance, as you work for the Federal Motor Transport Authority, to find out where the vehicle with **body part number** “K5-112-1122-79” was registered.

**Strategy**

1- Check the file names manually and see the logic.

2- Check the files Bestandteile_Fahrzeuge_X, find the vehicle ID through the given body part ID.

3- Cross check in the matching Fahrzeuge_X file, might be useful later too.

4- Check the registration data

5- Check the location data

**Imports:**

In [41]:
import pandas as pd

**Check, if the file contains the information we need**

In [42]:
df = pd.read_csv("data/Fahrzeug/Bestandteile_Fahrzeuge_OEM1_Typ11.csv", sep = ";")
df.head()

,Unnamed: 0,ID_Karosserie,ID_Schaltung,ID_Sitze,ID_Motor,ID_Fahrzeug
0,1,K4-112-1121-3,K3SG1-105-1051-32,K2LE1-109-1091-2,K1BE1-101-1011-7,11-1-11-1
1,2,K4-112-1121-4,K3SG1-105-1051-141,K2ST1-109-1092-5,K1BE1-101-1011-12,11-1-11-2
2,3,K4-112-1121-7,K3SG1-105-1051-106,K2ST1-109-1092-57,K1BE1-101-1011-38,11-1-11-3
3,4,K4-112-1121-9,K3SG1-105-1051-21,K2ST1-109-1092-91,K1BE1-101-1011-97,11-1-11-4
4,5,K4-112-1121-11,K3SG1-105-1051-59,K2ST1-109-1092-4,K1BE1-101-1011-65,11-1-11-5

**-> We understand that we need to check for ID_Karosserie**

In [43]:
body_part_number = "K5-112-1122-79"

bestandteile_files = ["OEM1_Typ11.csv", "OEM1_Typ12.csv", "OEM2_Typ21.csv", "OEM2_Typ22.csv"]

for i in bestandteile_files:
    body_parts = pd.read_csv("data/Fahrzeug/Bestandteile_Fahrzeuge_" + i, sep = ";")
    check = body_parts[body_parts["ID_Karosserie"] == body_part_number]
    if len(check) > 0:
        print(check)
        break

    Unnamed: 0   ID_Karosserie        ID_Schaltung            ID_Sitze  \
81          82  K5-112-1122-79  K3SG1-105-1051-129  K2ST1-109-1092-519

              ID_Motor ID_Fahrzeug
81  K1BE1-104-1041-409  12-1-12-82

**-> We have found the matching row**

In [44]:
id_vehicle = check["ID_Fahrzeug"].values[0]
print(id_vehicle)

12-1-12-82

In [45]:
vehicles = pd.read_csv("data/Fahrzeug/Fahrzeuge_OEM1_Typ12.csv", sep = ";")
vehicles.head()

,Unnamed: 0,X1,ID_Fahrzeug,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,1,1,12-1-12-1,2008-11-19,1,12,0,NaN,0
1,2,2,12-1-12-2,2008-11-19,1,12,0,NaN,0
2,3,3,12-1-12-3,2008-11-19,1,12,0,NaN,0
3,4,4,12-1-12-4,2008-11-19,1,12,0,NaN,0
4,5,5,12-1-12-5,2008-11-19,1,12,0,NaN,0

In [46]:
check_vehicle = vehicles[vehicles["ID_Fahrzeug"] == id_vehicle]
check_vehicle

,Unnamed: 0,X1,ID_Fahrzeug,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
81,82,82,12-1-12-82,2008-11-21,1,12,0,NaN,0

**-> The vehicle was produced before 2010, so the information we found is probably correct.**

In [47]:
registration = pd.read_csv("data/Zulassungen/Zulassungen_alle_Fahrzeuge.csv", sep = ";")
registration.head()

   Unnamed: 0   IDNummer Gemeinden   Zulassung
0      408097  11-1-11-1   DRESDEN  2009-01-01
1      408098  11-1-11-2   DRESDEN  2009-01-01
2           1  12-1-12-1   LEIPZIG  2009-01-01
3           2  12-1-12-2   LEIPZIG  2009-01-01
4           3  12-1-12-3  DORTMUND  2009-01-01

In [48]:
find_registration = registration[registration["IDNummer"] == id_vehicle] 
find_registration

     Unnamed: 0    IDNummer     Gemeinden   Zulassung
223          82  12-1-12-82  ASCHERSLEBEN  2009-01-02

In [49]:
vehicle_registered_in = find_registration["Gemeinden"].values[0]
vehicle_registered_in

'ASCHERSLEBEN'

**-> Location**

In [50]:
geodata = pd.read_csv("data/Geodaten/Geodaten_Gemeinden_v1.2_2017-08-22_TrR.csv", sep = ";")
geodata

,Unnamed: 0,X,Postleitzahl,Gemeinde,Laengengrad,Breitengrad
0,1,1,1067,DRESDEN,"13,736883","51,051697"
1,2,2,1445,RADEBEUL,"13,659342","51,105975"
2,3,3,1454,RADEBERG,"13,921969","51,116404"
3,4,4,1454,WACHAU,"13,904681","51,160116"
4,5,5,1458,OTTENDORF OKRILLA,"13,831724","51,187617"
...,...,...,...,...,...,...
7770,7771,7771,99994,SCHLOTHEIM,"10,65856","51,246183"
7771,7772,7772,99996,MENTERODA,"10,560617","51,307257"
7772,7773,7773,99996,OBERMEHLER,"10,596955","51,270273"
7773,7774,7774,99998,WEINBERGEN,"10,53003","51,199997"
7774,7775,7775,99998,KOERNER,"10,587315","51,231395"

In [51]:
aschersleben_details = geodata[geodata["Gemeinde"] == "ASCHERSLEBEN"]
aschersleben_details

     Unnamed: 0    X  Postleitzahl      Gemeinde Laengengrad Breitengrad
393         394  394          6449  ASCHERSLEBEN   11,455041   51,756034

In [52]:
aschersleben_postcode = aschersleben_details["Postleitzahl"].values[0]
aschersleben_longitude = aschersleben_details["Laengengrad"].values[0]
aschersleben_latitude = aschersleben_details["Breitengrad"].values[0]

In [53]:
print(f"The vehicle {id_vehicle} containing body part with id {body_part_number} is registered in {vehicle_registered_in}"
      f", post code: {aschersleben_postcode}, longitude: {aschersleben_longitude} latitude: {aschersleben_latitude}")

The vehicle 12-1-12-82 containing body part with id K5-112-1122-79 is registered in ASCHERSLEBEN, post code: 6449, longitude: 11,455041 latitude: 51,756034